### ISSUE TITLE
duplicate entry: javax/inject/Inject.class

### ISSUE THREAD

**Issue by arhmnsh** [JetBridge-io/react-native-obd2#1]
Trying to run the *example* project.
Getting error:
`Error:Execution failed for task ':app:transformClassesWithJarMergingForDebug'.`
`> com.android.build.api.transform.TransformException: java.util.zip.ZipException: duplicate entry: javax/inject/Inject.class`

<img width="793" alt="screen shot 2017-03-02 at 8 10 20 pm" src="https://cloud.githubusercontent.com/assets/1363724/23518393/54979576-ff84-11e6-884c-11422a71565b.png">

**Comment by pewh** [comment]
Have you solve this? I face same issue to

**Comment by yongho-jetbridge** [comment]
Not yet because of business trip. Soon, I'll patch it.

**Comment by SarasArya** [comment]
Even I am facing same issue. What is the solution for this?

**Comment by pewh** [comment]
I don't have try this but it seems the solution is http://stackoverflow.com/questions/43277745/error-while-compiling-react-native-duplicate-entry-javax-inject-inject-class

**Comment by SarasArya** [comment]
It did not work. Can you try it as well? I have replied on the answer, let us see what the author has to say about it.

**Comment by yongho-jetbridge** [comment]
Hi, all.
Finally, I am back to my hometown and fixed issue.
Please try it again.
