### ISSUE TITLE
What kind of data can be obtained via this library?

### ISSUE THREAD

**Issue by ddobby94** [JetBridge-io/react-native-obd2#6]
I am just intrested what datas will I see before ordering the bluetooth device.

**Comment by ddobby94** [comment]
still interested. Anyone?

**Comment by Michaelvilleneuve** [comment]
You should see the raw data coming from the obd2 port. Meaning that plugged to a car and with some reverse engineering you might be able to retrieve lots of informations about your car including :
- speed
- mileage
- engine faults


Edit: Here is a screenshot of a data output

<img width="1009" alt="capture d ecran 2018-03-06 a 22 16 20" src="https://user-images.githubusercontent.com/4990201/37058861-1fd0fbe0-218c-11e8-8102-21f268881bb5.png">
