### ISSUE TITLE
undefined is not an object (evaluating '_reactNative.ViewPropTypes.style')

### ISSUE THREAD

**Issue by barcode11** [JetBridge-io/react-native-obd2#7]
I have followed your installation instructions but when I do 
```react-native run-android```
I get the error mentioned in the title and heres an image as well from the emulator.
![image](https://user-images.githubusercontent.com/30638016/28848082-4e26f0c0-771a-11e7-8757-6481ee2d7606.png)

Any hints on this?

**Comment by mdhanju** [comment]
From error looks like `react-native-router-flux error`
Try using `"react-native-router-flux": "3.37.0"` in package.json

**Comment by barcode11** [comment]
@mdhanju thanks that fixed the issue

**Comment by yongho-jetbridge** [comment]
Thanks to all.
